import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navigation from "@/components/Navigation"
import { ThemeProvider } from '@/contexts/ThemeContext'
import { UserProvider } from '@/contexts/UserContext'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider>
          <UserProvider>
          <div className="min-h-screen flex flex-col w-screen">
            <header className="flex gap-4 h-16 content-center justify-center">
              <Navigation />
            </header>
            <main className="flex-1 p-6">
              {children}
            </main>
            <footer className="bg-[#333] w-full text-white p-4 text-center">
              <p>© 2026 haha的进步记录. All rights reserved.</p>
            </footer>
          </div>
          </UserProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
